### ISSUE TITLE
Missing method

### ISSUE THREAD

**Issue by jamesholcomb** [baynezy/Html2Markdown#5] opened 2015-11-06 15:45 UTC
Getting this error after updating to 1.0.3
````
System.MissingMethodException : Method not found: 'Void LinqExtensions.EachExtension.Each(System.Collections.Generic.IEnumerable`1<!!0>, System.Action`1<!!0>)'.
````
Updating `LinqExtensions` to 0.0.1.14396 fixes it.

**Comment by baynezy** [comment] 2015-11-06 20:03
James,
Thanks for your contribution. I am having trouble replicating this though. I have created a new project and installed the previous version via `Nuget`;

    Install-Package Html2Markdown -Version 1.0.2.29508

Then I update to the latest:

    Update-Package Html2Markdown

This brings down the latest version of `LinqExtensions`.

	PM> Update-Package Html2Markdown
	Updating 'Html2Markdown' from version '1.0.2.29508' to '1.0.3.11422' in project 'ConsoleApplication1'.
	Removing 'Html2Markdown 1.0.2.29508' from ConsoleApplication1.
	Successfully removed 'Html2Markdown 1.0.2.29508' from ConsoleApplication1.
	Adding 'LinqExtensions 0.0.1.14396' to ConsoleApplication1.
	Installing 'LinqExtensions 0.0.1.14396'.
	Successfully installed 'LinqExtensions 0.0.1.14396'.
	Successfully added 'LinqExtensions 0.0.1.14396' to ConsoleApplication1.
	Adding 'Html2Markdown 1.0.3.11422' to ConsoleApplication1.
	Installing 'Html2Markdown 1.0.3.11422'.
	Successfully installed 'Html2Markdown 1.0.3.11422'.
	Successfully added 'Html2Markdown 1.0.3.11422' to ConsoleApplication1.
	Uninstalling 'Html2Markdown 1.0.2.29508'.
	Successfully uninstalled 'Html2Markdown 1.0.2.29508'.


Can you tell me how you managed to get the error?

Thanks again.

**Comment by jamesholcomb** [comment] 2015-11-06 20:40
I believe I had updated from a version prior to 1.0.2.

I was able to repro by creating a new console app, then installing 1.0.3

````
PM> Install-Package Html2Markdown
Attempting to gather dependencies information for package 'Html2Markdown.1.0.3.11422' with respect to project 'html2md_test', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'Html2Markdown.1.0.3.11422' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Html2Markdown.1.0.3.11422'
Resolved actions to install package 'Html2Markdown.1.0.3.11422'
Adding package 'LinqExtensions.0.0.1.14054' to folder 'C:\Users\jamesholcomb\Documents\Visual Studio 2015\Projects\html2md_test\packages'
Added package 'LinqExtensions.0.0.1.14054' to folder 'C:\Users\jamesholcomb\Documents\Visual Studio 2015\Projects\html2md_test\packages'
Added package 'LinqExtensions.0.0.1.14054' to 'packages.config'
Successfully installed 'LinqExtensions 0.0.1.14054' to html2md_test
Adding package 'Html2Markdown.1.0.3.11422' to folder 'C:\Users\jamesholcomb\Documents\Visual Studio 2015\Projects\html2md_test\packages'
Added package 'Html2Markdown.1.0.3.11422' to folder 'C:\Users\jamesholcomb\Documents\Visual Studio 2015\Projects\html2md_test\packages'
Added package 'Html2Markdown.1.0.3.11422' to 'packages.config'
Successfully installed 'Html2Markdown 1.0.3.11422' to html2md_test
PM> 
````
Note the installed version of LinqExtensions

**Comment by baynezy** [comment] 2015-11-06 21:02
@jamesholcomb that is very strange. If I do the exact same command I get the following:-

	PM> Install-Package Html2Markdown
	Attempting to resolve dependency 'LinqExtensions'.
	Installing 'LinqExtensions 0.0.1.14396'.
	Successfully installed 'LinqExtensions 0.0.1.14396'.
	Installing 'Html2Markdown 1.0.3.11422'.
	Successfully installed 'Html2Markdown 1.0.3.11422'.
	Adding 'LinqExtensions 0.0.1.14396' to ConsoleApplication1.
	Successfully added 'LinqExtensions 0.0.1.14396' to ConsoleApplication1.
	Adding 'Html2Markdown 1.0.3.11422' to ConsoleApplication1.
	Successfully added 'Html2Markdown 1.0.3.11422' to ConsoleApplication1.

What version of Visual Studio are you using? I am on Visual Studio Professional 2012.

**Comment by jamesholcomb** [comment] 2015-11-06 21:15
Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

ASP.NET and Web Tools   14.0.60814.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GhostDoc   4.9.15086.0
GhostDoc automatically generates XML documentation comments.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
Copyright © 2011-2015, Eric Woodruff, All Rights Reserved.
https://GitHub.com/EWSoftware/SHFB

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

VS2015 GoToDefinition Fix   1.0
Fixes the "One or more errors occurred" error, which appears in VS2015, when you triyng to use the "Go to definition (F12)" command on a referenced assembly in C#

**Comment by baynezy** [comment] 2015-11-06 21:18
@jamesholcomb - I think the issue is that NuGet is resolving to the lowest package that meets my version in my dependencies.

https://nuget.codeplex.com/wikipage?title=Dependency%20Resolution

What you are seeing is the default behaviour. I am going to update the nuspec reference, which I am hoping will solve this.

**Comment by baynezy** [comment] 2015-11-06 21:24
@jamesholcomb - I have updated NuGet can you try again?

**Comment by jamesholcomb** [comment] 2015-11-06 21:26
That worked.

**Comment by baynezy** [comment] 2015-11-06 21:33
Thanks for your help @jamesholcomb

**Closed by baynezy** 2015-11-06 21:33 UTC
Labels: bug

**Comment by baynezy** [comment] 2015-11-06 22:20
I'd be interested to know what application you are using Html2Markdown for. If you are willing to share.

**Comment by jamesholcomb** [comment] 2015-11-06 23:49
I use it for converting VS XML doc to markdown.

**Comment by baynezy** [comment] 2015-11-06 23:52
Ah that is really interesting, thank you. Nice to know it is of use to people.

**Comment by jamesholcomb** [comment] 2015-11-07 00:06
Thanks for writing it :-)
